### PR TITLE
Add UU-dissertation-template

### PR DESCRIPTION
**Pull request by RoelBrouwer**
Please ensure your pull request adheres to the following guidelines:

- [x] Why do you think your project is a great addition? Please describe how it is useful or inspirational to other researchers.
   This template can be used by PhD students that write their thesis in LaTeX. It provides the basic required elements and instructions on how to expand on that or adapt it.
- [x] Use the following format for adding repositories: `- [repository_name](repository_link) - short description of the repository`
- [x] Repositories should be added alphabetically in the relevant category.
- [x] New categories or improvements to the existing categorization are welcome.
  I currently listed it under "Research project management". This is the best fit among the existing categories, but it is not perfect. Adding a new category would probably mean that this repository would be in a category of its own (something like "Research output templates"). I'm not sure if that is the way to go either.
- [ ] For collaboration groups, add only the github organization and a description of the organization.

Thanks for contributing!

### CODE REVIEW

**Comment by kequach** [comment]
Hi @RoelBrouwer, I think project management is fine as a category. Thanks for your contribution!

**Review by kequach — APPROVED** [review]

**Review by jelletreep — APPROVED** [review]

**Review by kequach — APPROVED** [review]

**Comment by jelletreep** [comment]
@kequach @J535D165 , something is going wrong with the approvals. It still says there is 1 approval although there are 2. Merging is still blocked for me. Can one of you look into this?

**Comment by kequach** [comment]
@jelletreep it looks like my approval doesn't work. My first guess would be that I don't have permissions anymore

**Comment by jelletreep** [comment]
I don't have admin rights in this repo, so I cannot fix it. @J535D165 , could you look into this?

**Pull request merged**
