### PR TITLE
add oceanexplorer?

### PR DESCRIPTION
**Pull request by MartinSchobben**
Hi awesome-utrecht-university maintainers,

I would like to contribute the following R package/shiny app that I worked on over the last months.

I think the package highlights some best practices for R package and shiny app development. It includes short and long documentation, R code/shiny app composed of modular components, unit tests, CI for installation checks, testing, and deployment of the website and app.

Thanks for considering!
 
Please ensure your pull request adheres to the following guidelines:

- [] Why do you think your project is a great addition? Please describe how it is useful or inspirational to other researchers.
- [ ] Use the following format for adding repositories: `- [repository_name](repository_link) - short description of the repository`
- [ ] Repositories should be added alphabetically in the relevant category.
- [ ] New categories or improvements to the existing categorization are welcome.
- [ ] For collaboration groups, add only the github organization and a description of the organization.

Thanks for contributing!

### CODE REVIEW

**Comment by kequach** [comment]
Hi @MartinSchobben, thank you for the pull request. It looks like an awesome repository. I think you deleted the .gitignore file by accident though, could you restore that?

**Comment by MartinSchobben** [comment]
Hi @kequach don't know what happened there, but I restored the .gitignore file.

**Review by J535D165 — APPROVED** [review]
Nice contribution. 

I would love to have a chat on the API design one day :) Any plans to use S3 classes?

**Comment by J535D165** [comment]
Thanks!

**Comment by MartinSchobben** [comment]
> Nice contribution.
> 
> I would love to have a chat on the API design one day :) Any plans to use S3 classes?

I did create some functions using class based dispatch, but I have not defined a new class for the package. I rather use the sf and stars classes. Let me know when you want to talk!

**Pull request merged**
