### PR TITLE
Add ShinyEducation project

### PR DESCRIPTION
**Pull request by VeenDuco**
Under the education and workshop section

Please ensure your pull request adheres to the following guidelines:

- [x] Why do you think your project is a great addition? Please describe how it is useful or inspirational to other researchers. **The project is useful for other teachers. The applications are meant to help explain statistical techniques and can be used by students as additional tools to facilitate learning.**
- [x] Use the following format for adding repositories: `- [repository_name](repository_link) - short description of the repository` **Check**
- [x] Repositories should be added alphabetically in the relevant category. **Check**
- [x] New categories or improvements to the existing categorization are welcome. **not relevant**
- [x] For collaboration groups, add only the github organization and a description of the organization. **not relevant**

Thanks for contributing!

### CODE REVIEW

**Comment by jelletreep** [comment]
Hi @VeenDuco, Thank you for this Pull Request, I will be happy to merge it.
I think your work could benefit from adding a [license](https://choosealicense.com/) and [citation instructions](https://fair-software.nl/recommendations/citation). By adding those you will at the same time meet the 4/5 fair software criteria that was used for composing the initial version of this list :smiley:

**Comment by VeenDuco** [comment]
Hi @jelletreep, Thanks for the helpful feedback. Both suggestions should be fixed now. What is the 5th criteria that I'm still missing? : )

**Comment by jelletreep** [comment]
Great, I will merge then!
@VeenDuco, good question haha there are several lists with criteria for this and I am actually not sure which one was used to create the initial awesome list. On [fair-software.nl](https://fair-software.nl/recommendations/checklist), step 5 would be to use a software quality checklist, but for your project this is not relevant I think. You could do this for the individual shiny apps, but not sure if it would be worth the effort.

**Comment by kequach** [comment]
Hi @jelletreep @VeenDuco, to answer your question regarding the checklist: Only the OpenSSF Best Practices checklist gets counted by the [howfairis ](https://github.com/fair-software/howfairis) tool which we used. See ASReview for example: https://bestpractices.coreinfrastructure.org/en/projects/4755
However, this is really not feasible for most projects and most projects also don't have this list. Therefore, it's a criteria that can be somewhat neglected. Having a license and citation instructions are much more important as Jelle has pointed out 🙂

**Pull request merged**
